version: "3"
services:
  scraper:
    container_name: scraper
    image: lonelydaoist/scraper
    environment:
      - DB_STRING=mongodb://db:27017/
      - START_PAGE=1
      - END_PAGE=100
    depends_on:
      - db
  db:
    container_name: scraper_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
      - ./db/config:/data/configdb
